CREATE SEQUENCE IF NOT EXISTS USER_SEQ START 1 INCREMENT 1;

CREATE TABLE IF NOT EXISTS PUBLIC.USER
(
    ID              BIGINT       NOT NULL PRIMARY KEY DEFAULT NEXTVAL('USER_SEQ'),
    USERNAME        VARCHAR(255) NOT NULL UNIQUE,
    EMAIL           VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

-- ADD AN INDEX ON THE USERNAME COLUMN FOR FASTER LOOKUPS
CREATE INDEX IF NOT EXISTS IDX_USER_USERNAME ON PUBLIC.USER (ID, USERNAME);

-- ADD USER INFORMATION
INSERT INTO  PUBLIC.USER (USERNAME, EMAIL)
VALUES ('admin', 'admin@mail.com'),
       ('username1', 'username1@mail.com'),
       ('username2', 'username2@mail.com');