CREATE SEQUENCE IF NOT EXISTS TRANSACTION_SEQ START 1 INCREMENT 1;

CREATE TABLE IF NOT EXISTS PUBLIC.TRANSACTION
(
    TRANSACTION_ID BIGINT       NOT NULL PRIMARY KEY DEFAULT NEXTVAL('TRANSACTION_SEQ'),
    USER_ID        BIGINT       NOT NULL,
    AMOUNT         VARCHAR(255) NOT NULL,
    CREATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TRANSACTION_USER FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USER (ID)
);

CREATE INDEX IF NOT EXISTS IDX_USER_USERNAME ON PUBLIC.USER (ID, USERNAME);
